config/routes.rb
Rails.application.routes.draw do




  resources :bookings
  resources :economies
  resources :businesses
  resources :firsts

  resources :flights do
    resources :firsts do
      resources :seats
    end
  end

  resources :flights do
    resources :businesses do
      resources :seats
    end
  end

  resources :flights do
    resources :economies do
      resources :seats
    end
  end

  resources :flights do
    resources :bookings
  end

  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  #post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/createnewfirst', to: 'firsts#new'
  post '/createnewfirst', to: 'firsts#create'
  get 'createfirstseat', to: 'seats#new'
  post 'createfirstseat', to: 'seats#create'
  get 'createbusinessseat', to: 'seats#bnew'
  post 'createbusinessseat', to: 'seats#bcreate'
  #get '/activate',   to: 'account_activations#activate'
  get '/dashboard', to: 'bookings#userbooking'

  get '/findflight', to: 'flights#findflight'
  post '/findflight', to: 'flights#findflight'

  get '/bookseat', to: 'bookings#bookseat'
  post '/bookseat', to: 'bookings#bookseat'

  get '/seatselect', to: 'bookings#seatselect'
  post '/seatselect', to: 'bookings#seatselect'

  get '/confirm', to: 'bookings#confirm'

  get '/bookings/:booking_id/upgrade', to: 'bookings#upgradeseatnew', as: 'upgradeseat'
  post '/bookings/:booking_id/upgrade', to: 'bookings#upgradeseatcreate'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/flight.rb
class Flight < ApplicationRecord
  has_one :first, dependent: :destroy
  has_one :business, dependent: :destroy
  has_one :economy, dependent: :destroy
  has_many :bookings, dependent: :destroy
  before_save   :downcase_source_and_destination
  validates :name, presence: true
  validates :ftype, presence: true
  validates :start_time, presence: true, if: :validstart
  validates :end_time, presence: true, if: :validend
  validates :from, presence: true, case_sensitive: false
  validates :destination, presence: true, if: :samedestination, case_sensitive: false

  def validstart
    if (start_time < Time.current)
      errors.add(:start_time)
    end
  end

  def validend
    (!end_time.nil? ) ? true : errors.add(:end_time)
    if (end_time.to_time < start_time.to_time + 1500)
      errors.add(:end_time, "should be greater or equal to 15min")
    end
  end

  def samedestination
    if(from.casecmp(destination) == 0)
      errors.add(:destination, "cannot be same as From ")
    end
  end

  def downcase_source_and_destination
    self.from = from.downcase
    self.destination = destination.downcase
  end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user
  before_action :admin, only: [:new, :edit, :create, :update, :destroy]
  include SessionsHelper
  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
  end

  def findflight
    @from = params[:from].downcase
    @destination = params[:destination].downcase
    @flights = Flight.where(:from => @from, :destination => @destination)
    if (@flights.exists?)
      render :findflight
    else
      flash[:info] = "Sorry no flights to that route yet"
      redirect_to root_path
    end
  end


  # GET /flights/1
  # GET /flights/1.json
  def show
    @flights = Flight.all
    @first = @flight.first
    @business = @flight.business
    @economy = @flight.economy
    if @first
      @fseat = @first.seats
    end
    if @business
      @bseat = @business.seats
    end
    if @economy
      @eseat = @economy.seats
    end
  end

  # GET /flights/new
  def new
    @flight = Flight.new
end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)
    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:name, :ftype, :from, :destination, :start_time, :end_time, :base_price)
    end


end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_with(model: flight, local: true) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :flight_type %>
    <%= form.text_field :ftype %>
  </div>

  <div class="field">
    <%= form.label :from %>
    <%= form.text_field :from %>
  </div>

  <div class="field">
    <%= form.label :destination %>
    <%= form.text_field :destination %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="field">
    <%= form.label :base_price %>
    <%= form.text_field :base_price %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/findflight.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>From</th>
      <th>Destination</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.name %><%= " " %><%= flight.ftype %></td>
        <td><%= flight.from %></td>
        <td><%= flight.destination %></td>
        <td><%= readable_time(flight.start_time) %></td>
        <td><%= readable_time(flight.end_time) %></td>
        <% if is_admin? %>
        <td><%= link_to 'Show', flight %></td>
        <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
        <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
        <td><%= link_to 'Book this Flight', new_flight_booking_path(:flight_id => flight.id) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/flights/index.html.erb
<h1>Flights</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>From</th>
      <th>Destination</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

     <% if is_admin? %>
         <% @flights.each do |flight| %>
           <tr>
             <td><%= flight.name %><%= " " %><%= flight.ftype %></td>
             <td><%= flight.from %></td>
             <td><%= flight.destination %></td>
             <td><%= readable_time(flight.start_time) %></td>
             <td><%= readable_time(flight.end_time) %></td>
             <td><%= link_to 'Show', flight %></td>
             <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
             <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
           </tr>
        <% end %>
     <% else%>
          <% @flights.each do |flight| %>
            <tr>
              <% if (flight.business.nil? || flight.first.nil? || flight.economy.nil? ) %>
              <% else %>
              <td><%= flight.name %><%= " " %><%= flight.ftype %></td>
              <td><%= flight.from %></td>
              <td><%= flight.destination %></td>
              <td><%= readable_time(flight.start_time) %></td>
              <td><%= readable_time(flight.end_time) %></td>
              <td><%= link_to 'Book this Flight', new_flight_booking_path(:flight_id => flight.id) %></td>
            </tr>
          <% end %>
        <% end %>
      <%end%>
  </tbody>
</table>
<br>

<% if is_admin? %>
   <%= link_to 'New Flight', new_flight_path %>
<% end %>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<% if is_admin? %>
<p>
  <strong>Name:</strong>
  <%= @flight.name %> <%= @flight.ftype %>
</p>

<p>
  <strong>From:</strong>
  <%= @flight.from %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @flight.destination %>
</p>

<p>
  <strong>Start time:</strong>
  <%= readable_time(@flight.start_time) %>
</p>

<p>
  <strong>End time:</strong>
  <%= readable_time(@flight.end_time) %>
</p>

  <% if @first %>
    <%= render 'firsts/show' %>
    <br>
          <% if @fseat.count>0 %>
          <% else %>
               <%= link_to 'Confirm Seat Config for First Class', new_flight_first_seat_path(@flight, @first) %>
          <% end %>
  <% else %>
  <%= link_to 'Create First class', new_flight_first_path(@flight) %>
  <br>
  <%end%>
<br>


 <% if @business %>
    <%= render 'businesses/show' %>
<% else %>
    <%= link_to 'Create Business class', new_flight_business_path(@flight) %>
    <br>
<% end %>
<br>

<% if @economy %>
   <%= render 'economies/show' %>
<% else %>
   <%= link_to 'Create Economy class', new_flight_economy_path(@flight) %>
<% end %>

<br>
<%= render 'seats/index' %>

<% else %>
<%= link_to 'Go back to flights', flights_path %>
<% end %>