config/routes.rb
Rails.application.routes.draw do




  resources :bookings
  resources :economies
  resources :businesses
  resources :firsts

  resources :flights do
    resources :firsts do
      resources :seats
    end
  end

  resources :flights do
    resources :businesses do
      resources :seats
    end
  end

  resources :flights do
    resources :economies do
      resources :seats
    end
  end

  resources :flights do
    resources :bookings
  end

  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  #post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/createnewfirst', to: 'firsts#new'
  post '/createnewfirst', to: 'firsts#create'
  get 'createfirstseat', to: 'seats#new'
  post 'createfirstseat', to: 'seats#create'
  get 'createbusinessseat', to: 'seats#bnew'
  post 'createbusinessseat', to: 'seats#bcreate'
  #get '/activate',   to: 'account_activations#activate'
  get '/dashboard', to: 'bookings#userbooking'

  get '/findflight', to: 'flights#findflight'
  post '/findflight', to: 'flights#findflight'

  get '/bookseat', to: 'bookings#bookseat'
  post '/bookseat', to: 'bookings#bookseat'

  get '/seatselect', to: 'bookings#seatselect'
  post '/seatselect', to: 'bookings#seatselect'

  get '/confirm', to: 'bookings#confirm'

  get '/bookings/:booking_id/upgrade', to: 'bookings#upgradeseatnew', as: 'upgradeseat'
  post '/bookings/:booking_id/upgrade', to: 'bookings#upgradeseatcreate'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  before_save :generate_bpnr
  before_destroy :restore
  has_many :selectseats, dependent: :destroy
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                  format: { with: VALID_EMAIL_REGEX }
  validates :seats, presence: true, if: :validseat


  def restore
        seats1 = Seat.where(:booking_id => id)
        seats1.each do |seat|
          seat.update_attributes(booking_id: nil,available: true)
        end
     	end


    def validseat

      if(seats == 0 || seats ==nil || seats < 0 )
        errors.add(:seats, "Number of seats should be atleast 1")
      else

      if(flight.first.num_of_seats < seats)
        errors.add(:seats, "Seats exceeding the availability")
      end

      if(flight.business.num_of_seats < seats)
        errors.add(:seats, "Seats exceeding the availability")
      end

      if(flight.economy.num_of_seats < seats)
        errors.add(:seats, "exceeding the availability")
      end
    end
    end


class << self
   # Returns a random token.
    def new_token
      SecureRandom.hex(4)
    end

end

private

def generate_bpnr
  self.pnr  = Booking.new_token
end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :update, :destroy]
  before_action :logged_in_user
  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.where(:user_id=>current_user.id ).order("created_at")
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
    @seats= Seat.where(:booking_id => @booking.id)
    if (!@booking.business_id.nil? )
       @business = Business.where(id: @booking.business_id).first
    elsif (!@booking.economy_id.nil? )
      @economy = Economy.where(id: @booking.economy_id).first
    elsif (!@booking.first_id.nil? )
      @first = First.where(id: @booking.first_id).first
    end
      @flight = Flight.where(id: @booking.flight_id).first
    @business1 = Business.where(flight_id: @flight.id).first
   @economy1 = Economy.where(flight_id: @flight.id).first
   @first1 = First.where(flight_id: @flight.id).first
  end


  def userbooking
    @bookings = Booking.where(:user_id=>current_user.id )
  end


   def bookseat
     @pnr = params[:pnr]
     @booking = Booking.where(:pnr => params[:pnr]).last
     if @booking.nil?
       flash[:info] = "Enter a valid PNR number"
       redirect_to bookings_path
     elsif (@booking.booked == true)
       flash[:info] = "Seats are already booked"
       redirect_back(fallback_location: root_path)
     else
         @booking.selectseats.destroy_all
         if (!@booking.business_id.nil? )
            @seats = Seat.where(business_id: @booking.business_id).order("id")
            @business = Business.where(flight_id: @booking.flight_id).first

         elsif (!@booking.economy_id.nil? )
               @seats = Seat.where(economy_id: @booking.economy_id).order("id")
               @economy = Economy.where(flight_id: @booking.flight_id).first

         elsif (!@booking.first_id.nil? )
                  @seats = Seat.where(first_id: @booking.first_id).order("id")
                  @first = First.where(flight_id: @booking.flight_id).first
         end
      end
   end


   def seatselect
     @booking = Booking.find(params[:booking_id])
     @seat = Seat.find(params[:seat_id])
    if (!@booking.selectseats.where(:seatnumber => params[:seat_id]).exists?)
      @booking.selectseats.create(:seatnumber => params[:seat_id], :booking_id => @booking.id)
    else
      @x = Selectseat.where(:seatnumber => params[:seat_id])
      @x.destroy_all
    end

   end

   def confirm
     @booking = Booking.find(params[:booking_id])
     @seats = Seat.where(:seat_id => params[:id])
      @y = @booking.selectseats.count
     if (@y > @booking.seats || @y < @booking.seats)
       flash[:info] = "You have selected more/less seats"
       redirect_to @booking
     else
       @booking.update_column(:booked, true)
       flash[:success]="Booking has been successful"
        @booking.selectseats.each do |i|
          @selectedseat = Seat.find(i.seatnumber)
          @selectedseat.update_attributes(:booking_id => @booking.id, :available => false)
        end
       redirect_to @booking
     end

   end

  # GET /bookings/new
  def new
    @flight = Flight.find(params[:flight_id])
    @business1 = Business.where(flight_id: @flight.id).first
    @economy1 = Economy.where(flight_id: @flight.id).first
    @first1 = First.where(flight_id: @flight.id).first
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @flight = Flight.find(params[:flight_id])
    @booking = @flight.bookings.create(booking_params)
    @business1 = Business.where(flight_id: @flight.id).first
   @economy1 = Economy.where(flight_id: @flight.id).first
   @first1 = First.where(flight_id: @flight.id).first
    @y = @booking.seats
    respond_to do |format|
      if @booking.save
        if (!@booking.business_id.nil? )
          @business = Business.where(:flight_id => @booking.flight_id).last
          @x = @business.num_of_seats - @y
          @business.update_column(:num_of_seats, @x)
        elsif (!@booking.economy_id.nil? )
          @economy = Economy.where(:flight_id => @booking.flight_id).last
          @x = @economy.num_of_seats - @y
          @economy.update_column(:num_of_seats, @x)
        elsif (!@booking.first_id.nil? )
          @first = First.where(:flight_id => @booking.flight_id).last
          @x = @first.num_of_seats - @y
          @first.update_column(:num_of_seats, @x)
        end
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end


  def upgradeseatnew
    @booking = Booking.find(params[:booking_id])
    @flight = Flight.where(:id => @booking.flight_id ).last
    @first = First.where(:flight_id => @flight.id).last
    @business = Business.where(:flight_id => @flight.id).last
    @business = @flight.business
    @economy = @flight.economy
  end

  def upgradeseatcreate
    @previous_booking = Booking.find(params[:booking_id])
    @flight = Flight.where(:id => @previous_booking.flight_id ).last
    @y = @previous_booking.seats
    if (!@previous_booking.business_id.nil? )
      @business = Business.where(:flight_id => @previous_booking.flight_id).last
      @x = @business.num_of_seats + @y
      @business.update_column(:num_of_seats, @x)
    elsif (!@previous_booking.economy_id.nil? )
      @economy = Economy.where(:flight_id => @previous_booking.flight_id).last
      @x = @economy.num_of_seats + @y
      @economy.update_column(:num_of_seats, @x)
    elsif (!@previous_booking.first_id.nil? )
      @first = First.where(:flight_id => @previous_booking.flight_id).last
      @x = @first.num_of_seats + @y
      @first.update_column(:num_of_seats, @x)
    end

    @booking = @flight.bookings.create(booking_params)
    @z = @booking.seats
    respond_to do |format|
      if @booking.save
        if (!@booking.business_id.nil? )
          @business = Business.where(:flight_id => @booking.flight_id).last
          @x = @business.num_of_seats - @z
          @business.update_column(:num_of_seats, @x)
        elsif (!@booking.economy_id.nil? )
          @economy = Economy.where(:flight_id => @booking.flight_id).last
          @x = @economy.num_of_seats - @z
          @economy.update_column(:num_of_seats, @x)
        elsif (!@booking.first_id.nil? )
          @first = First.where(:flight_id => @booking.flight_id).last
          @x = @first.num_of_seats - @z
          @first.update_column(:num_of_seats, @x)
        end
        @previous_booking.destroy
        format.html { redirect_to bookings_path, notice: 'Your Seat is successfully changed .' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:economy_id, :business_id, :first_id, :flight_id, :name, :email, :pnr, :seats, :user_id, :classname, :search, :booked)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
  def get_flight_name(id)
    Flight.find(id).name
   end

   def get_flight_lname(id)
     Flight.find(id).ftype
    end


end

app/views/bookings/_form.html.erb
<%= form_for @booking, url: flight_bookings_path do |form| %>

  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>
      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form.hidden_field :user_id, value: current_user.id %>
<%= form.hidden_field :flight_id, value: @flight.id %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <h3> Choose a Class </h3>

  <div class="field">

    <% if @first1.nil? %>
    <% else %>
    <div class="flightclass">
        <div class="font20">  <%= form.label :'First class' %> </div>
        <%= @first1.num_of_seats %>  seats available
           <% if (@first1.num_of_seats <=0 )%>
           <% else %>
           <%= form.radio_button( :first_id, @first1.id ) %>
          <% end %>
    </div>
    <% end %>


    <% if @business1.nil? %>
    <% else %>
          <div class="flightclass">
          <div class="font20"><%= form.label :'Business class' %> </div>
          <%= @business1.num_of_seats %>  seats available
              <% if (@business1.num_of_seats <=0 )%>
              <% else %>
              <%= form.radio_button( :business_id, @business1.id)  %>
              <% end %>
          </div>
    <% end %>

   <% if @economy1.nil? %>
   <% else %>
   <div class="flightclass">
    <div class="font20"><%= form.label :'Economy class' %> </div>
    <%= @economy1.num_of_seats %>  seats available
        <% if (@economy1.num_of_seats <=0 )%>
        <% else %>
        <%= form.radio_button( :economy_id, @economy1.id ) %>
        <% end %>
  </div>
  <%end%>


  <div class="field">
    <%= form.label :seats %>
    <%= form.number_field :seats %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/bookings/bookseat.html.erb
<% if (!@booking.business_id.nil? ) %>
<strong><p>Business Class</p></strong>
<% elsif (!@booking.economy_id.nil? ) %>
<strong><p>Economy Class</p></strong>
<% elsif (!@booking.first_id.nil? ) %>
<strong><p>First Class</p></strong>
<% end %>

<table>
  <thead>
    <tr>
    </tr>
  </thead>

<% @x=1 %>
<% @y=0 %>

  <tbody>
    <% @seats.each do |seat| %>
      <% if seat.available? %>
        <% if (@booking.selectseats.size < @booking.seats) %>
           <div class="seatboxtrue">
           <%=link_to @x , seatselect_path(:seat_id => seat.id, :booking_id => @booking.id), remote: true, onclick:"this.classList.toggle('changecolor')",class:"seat", id:"counter" %>
        </div>
        <% else %>
          <%= @x %>
        <%end%>

        <% else %>
        <div class="seatboxfalse">
          <%= @x %>
       </div>

      <%end%>

        <% if @business %>
            <% if (@x % @business.seats_in_row == 0) %>
               <br>
            <%end%>
            <% if (@business.seats_in_row == 6 ) %>
                <% if (@x % 3 == 0 && @x % 6 != 0) %>
                   <div class="seatbreak"> </div>
                <%end%>
            <% end %>
        <% elsif @economy %>
            <% if (@x % @economy.seats_in_row == 0) %>
               <br>
               <% @y= @y + @economy.seats_in_row %>
                <%end%>
                <% if (@economy.seats_in_row == 10) %>
                   <% if ((@y -@x) % 3 == 0 && (@y -@x) % 6 != 0 && (@y -@x) % 9 != 0) || (@y -@x) % 7 ==0 %>
                      <div class="seatbreak"> </div>
                   <%end%>
               <% end%>
        <% elsif @first%>
            <% if (@x % @first.seats_in_row == 0) %>
               <br>
            <%end%>
        <%end%>
            <% @x = @x+1 %>



    <% end %>

  </tbody>
</table>

<%=link_to "Confirm", confirm_path(:booking_id=>@booking.id), class:"button"%>


<script>

</script>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<% if @bookings.nil? %>
<%= link_to "Book a Flight",   flights_path %>
<% else %>
<table>
  <thead>
    <tr>
      <th>Flight Name</th>
      <th>Name</th>
      <th>Pnr</th>
      <th>Seats</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= get_flight_name(booking.flight_id) %>
             <%= get_flight_lname(booking.flight_id) %></td>
        <td><%= booking.name %></td>
        <td><%= booking.pnr %></td>
        <td><%= booking.seats %></td>
        <td><%= link_to 'Show', booking %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class = "rightsection">
<%= form_tag(bookseat_path, method: :get) do %>
   <strong><p> Enter PNR </p></strong>
   <%= text_field_tag(:pnr, params[:pnr]) %>
   <%= submit_tag ("Search") %>
 <% end %>
</div>
<% end %>

<br>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @booking.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @booking.email %>
</p>

<p>
  <strong>Flight Name:</strong>
  <%= get_flight_name(@booking.flight_id)  %>
  <%= get_flight_lname(@booking.flight_id) %>
</p>


<p>
  <strong>Seats:</strong>
  <%= @booking.seats %>
</p>


<% if @booking.first_id %>
      <p>
        <strong>Class:</strong>
        First Class
      </p>
      <p>
        <strong>Price in rupees:</strong>
        <%= (@booking.seats) * (@first.first_price) %>
      </p>
<% end %>

<% if @booking.business_id %>
      <p>
        <strong>Class:</strong>
         Business Class
      </p>
      <p>
        <strong>Price in rupees:</strong>
        <%= (@booking.seats) * (@business.business_price) %>
      </p>
<% end %>

<% if @booking.economy_id %>
<p>
  <strong>Class:</strong>
   Economy Class

   <p>
     <strong>Price in rupees:</strong>
     <%= (@booking.seats) * (@economy.economy_price) %>
   </p>
</p>
<% end %>

<p>
  <strong>Pnr:</strong>
  <%= @booking.pnr %>
</p>

<% if @seats.count >0 %>
<p>
  <strong>Seat No:</strong>
  <% @seats.order("id").each do |s| %>
    <%= s.seatno%> <%= ','%>
  <% end %>
</p>
      <% if (!@booking.business_id.nil?) %>
            <% if (!@first1.nil?) %>
              <%= link_to 'Upgrade to First Class', upgradeseat_path(@booking) %>
            <% end %>
      <%else%>
            <% if @booking.first_id %>
            <%else%>
              <% if (!@first1.nil? || !@business.nil?) %>
                 <%= link_to 'Upgrade my seat', upgradeseat_path(@booking) %>
            <% end %>
            <%end%>
     <% end %>
  <% else %>
    <p> Book Seats with the provided PNR </p>
<% end%>


<%= link_to 'Back', bookings_path %>

app/views/bookings/upgradeseatnew.html.erb
<h2> Choose Class </h2>

<%= form_for(@booking, url: upgradeseat_path, method: "post") do |form| %>
<% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user.id %>
  <%= form.hidden_field :flight_id, value: @booking.flight_id %>
  <%= form.hidden_field :name, value: @booking.name %>
  <%= form.hidden_field :email, value: @booking.email %>
  <%= form.hidden_field :pnr, value: @booking.pnr %>
  <%= form.hidden_field :seats, value: @booking.seats %>


<div class="field">


 <% if (!@first.nil?) %>
  <div class="flightclass">
      <%= form.label :'First class' %>
      <%= @first.num_of_seats %>  seats available
      <% if (@first.num_of_seats > @booking.seats )%>
      <%= form.radio_button( :first_id, @first.id ) %>
      <% end %>
  </div>
<% end %>


  <% if(!@business.nil?) %>
        <% if (@booking.business_id.nil?) %>
          <div class="flightclass">
          <%= form.label :'Business class' %>
          <%= @business.num_of_seats %>  seats available
          <% if (@booking.flight.business.num_of_seats > @booking.seats) %>
            <% if (@business.num_of_seats > @booking.seats )%>
              <%= form.radio_button( :business_id, @business.id )  %>
            <%end%>
          <%end%>
        </div>
        <% end %>
  <% end %>


  </div>

<% if(!@business.nil? ) %>

    <% if (@business.num_of_seats > @booking.seats || @first.num_of_seats > @booking.seats )%>
      <div class="actions">
        <%= form.submit %>
      </div>
<% end %>
<% end %>
<% end %>

app/views/bookings/userbooking.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Pnr</th>
      <th>Seats</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<tbody>
<% @bookings.each do |booking| %>
  <tr>

    <td><%= booking.name %></td>
    <td><%= booking.email %></td>
    <td><%= booking.pnr %></td>
    <td><%= booking.seats %></td>
    <td><%= link_to 'Book Seats', '#' %> </td>
  </tr>
<% end %>
</tbody>
</table>