config/routes.rb
Rails.application.routes.draw do




  resources :bookings
  resources :economies
  resources :businesses
  resources :firsts

  resources :flights do
    resources :firsts do
      resources :seats
    end
  end

  resources :flights do
    resources :businesses do
      resources :seats
    end
  end

  resources :flights do
    resources :economies do
      resources :seats
    end
  end

  resources :flights do
    resources :bookings
  end

  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  #post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/createnewfirst', to: 'firsts#new'
  post '/createnewfirst', to: 'firsts#create'
  get 'createfirstseat', to: 'seats#new'
  post 'createfirstseat', to: 'seats#create'
  get 'createbusinessseat', to: 'seats#bnew'
  post 'createbusinessseat', to: 'seats#bcreate'
  #get '/activate',   to: 'account_activations#activate'
  get '/dashboard', to: 'bookings#userbooking'

  get '/findflight', to: 'flights#findflight'
  post '/findflight', to: 'flights#findflight'

  get '/bookseat', to: 'bookings#bookseat'
  post '/bookseat', to: 'bookings#bookseat'

  get '/seatselect', to: 'bookings#seatselect'
  post '/seatselect', to: 'bookings#seatselect'

  get '/confirm', to: 'bookings#confirm'

  get '/bookings/:booking_id/upgrade', to: 'bookings#upgradeseatnew', as: 'upgradeseat'
  post '/bookings/:booking_id/upgrade', to: 'bookings#upgradeseatcreate'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/first.rb
class First < ApplicationRecord
  belongs_to :flight
  has_many :seats
  validates :row, presence: true
  validates :seats_in_row, presence: true
  
end

app/controllers/firsts_controller.rb
class FirstsController < ApplicationController
  #before_action :set_first, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user
  # GET /firsts
  # GET /firsts.json
  def index
    @firsts = First.all
  end

  # GET /firsts/1
  # GET /firsts/1.json
  def show
    @flight = Flight.find(params[:flight_id])
    @first = @flight.first
  end

  # GET /firsts/new
  def new
    @flight = Flight.find(params[:flight_id])
    @first = First.new
  end

  # GET /firsts/1/edit
  def edit
  end

  # POST /firsts
  # POST /firsts.json
  def create
    @flight = Flight.find(params[:flight_id])
    @first = First.create(first_params)
    @flight.first = @first

    @x=1
    @first.row.times do |i|
      @first.seats_in_row.times do |i|
        @seat = @first.seats.create(seatno: @x)
        @x=@x+1
      end
     end
    respond_to do |format|
      if @first.save
        @first.update_attributes(num_of_seats: @first.seats_in_row * @first.row )
        format.html { redirect_to @flight, notice: 'Firstclass is created.' }
        format.json { render :show, status: :created, location: @first }
      else
        format.html { render :new }
        format.json { render json: @first.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /firsts/1
  # PATCH/PUT /firsts/1.json
  def update
    respond_to do |format|
      if @first.update(first_params)
        format.html { redirect_to @first, notice: 'First successfully updated.' }
        format.json { render :show, status: :ok, location: @first }
      else
        format.html { render :edit }
        format.json { render json: @first.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /firsts/1
  # DELETE /firsts/1.json
  def destroy
    @first.destroy
    respond_to do |format|
      format.html { redirect_to firsts_url, notice: 'First was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    #def set_first
      #@first = First.find(params[:id])
    #end

    # Never trust parameters from the scary internet, only allow the white list through.
    def first_params
      params.require(:first).permit(:row, :seats_in_row, :first_price)
    end
end

app/helpers/firsts_helper.rb
module FirstsHelper
end

app/views/firsts/_form.html.erb
<%= form_for First.new, url: flight_firsts_path do |form| %>

<% if first.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(first.errors.count, "error") %> prohibited this first from being saved:</h2>

    <ul>
    <% first.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <div class="field">
    <%= form.label :row %>
    <%= form.number_field :row %>
  </div>

  <div class="field">
    <%= form.label :seats_in_row %>
    <%= form.number_field :seats_in_row %>
  </div>

 <%= form.hidden_field :first_price, value: (@flight.base_price * 0.2) + @flight.base_price  %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/firsts/_show.html.erb
----------------------------
<h2> First Class </h2>
<p>
  <strong>Row:</strong>
  <%= @first.row %>
</p>

<p>
  <strong>Seats in row:</strong>
  <%= @first.seats_in_row %>
</p>


<p>
  <strong>Price:</strong>
  <%= @first.first_price %>
</p>

app/views/firsts/edit.html.erb
<h1>Editing First</h1>

<%= render 'form', first: @first %>

<%= link_to 'Show', @first %> |
<%= link_to 'Back', firsts_path %>

app/views/firsts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Firsts</h1>

<table>
  <thead>
    <tr>
      <th>Row</th>
      <th>Seats in row</th>
      <th>Fcpnr</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @firsts.each do |first| %>
      <tr>
        <td><%= first.row %></td>
        <td><%= first.seats_in_row %></td>
        <td><%= first.fcpnr %></td>
        <td><%= link_to 'Show', first %></td>
        <td><%= link_to 'Edit', edit_first_path(first) %></td>
        <td><%= link_to 'Destroy', first, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New First', new_first_path %>

app/views/firsts/new.html.erb
<h1>New First</h1>

<%= render 'form', first: @first %>

app/views/firsts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Row:</strong>
  <%= @first.row %>
</p>

<p>
  <strong>Seats in row:</strong>
  <%= @first.seats_in_row %>
</p>

<p>
  <strong>Fcpnr:</strong>
  <%= @first.fcpnr %>
</p>

<%= link_to 'Confirm Seat Config', new_flight_first_seat_path(@flight, @first) %>
<%= link_to 'Edit', edit_first_path(@first) %> |