config/routes.rb
Rails.application.routes.draw do




  resources :bookings
  resources :economies
  resources :businesses
  resources :firsts

  resources :flights do
    resources :firsts do
      resources :seats
    end
  end

  resources :flights do
    resources :businesses do
      resources :seats
    end
  end

  resources :flights do
    resources :economies do
      resources :seats
    end
  end

  resources :flights do
    resources :bookings
  end

  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  #post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/createnewfirst', to: 'firsts#new'
  post '/createnewfirst', to: 'firsts#create'
  get 'createfirstseat', to: 'seats#new'
  post 'createfirstseat', to: 'seats#create'
  get 'createbusinessseat', to: 'seats#bnew'
  post 'createbusinessseat', to: 'seats#bcreate'
  #get '/activate',   to: 'account_activations#activate'
  get '/dashboard', to: 'bookings#userbooking'

  get '/findflight', to: 'flights#findflight'
  post '/findflight', to: 'flights#findflight'

  get '/bookseat', to: 'bookings#bookseat'
  post '/bookseat', to: 'bookings#bookseat'

  get '/seatselect', to: 'bookings#seatselect'
  post '/seatselect', to: 'bookings#seatselect'

  get '/confirm', to: 'bookings#confirm'

  get '/bookings/:booking_id/upgrade', to: 'bookings#upgradeseatnew', as: 'upgradeseat'
  post '/bookings/:booking_id/upgrade', to: 'bookings#upgradeseatcreate'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "/custom.css" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
        <nav>
          <ul class="topnav">
            <li class="items"><%= link_to "Logo", root_path, id: "logo" %></li>
            <li class="items"><%= link_to "Find Flight",   root_path %></li>
            <% if logged_in? %>
            <% if is_admin? %>
            <li class="items"><%= link_to "Manage Flights",   flights_path %></li>
            <% else %>
            <li class="items"><%= link_to "All Flights",   flights_path %></li>
            <li class="items"><%= link_to "My Bookings",   bookings_path %></li>
            <%end%>
              <li class="dropdown rightitems">
                <a href="javascript:void(0)" class="dropbtn " data-toggle="dropdown">
                  Account </a>
                  <div class="dropdown-content">
                    <%= link_to "Profile", current_user %>
                    <%= link_to "Settings", edit_user_path(current_user) %>
                    <%= link_to "Log out", logout_path, method: :delete %>
                  </div>
            </li>

        <% else %>
          <li class="rightitems"><%= link_to "Log in", login_path %></li>
        <% end %>
        <li class="rightitems"><%= link_to "Help",   help_path %></li>
      </ul>
        </nav>

        <% flash.each do |message_type, message| %>
       <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
     <% end %>

    </header>

    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>